workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      java: 11
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install -g pnpm
          pnpm install
      - name: Build web assets
        script: |
          pnpm build
      - name: Sync with Capacitor
        script: |
          pnpm exec cap sync
      - name: Build Android APK
        script: |
          cd android
          ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
